language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - miraedbswo@gmail.com
env:
  global:
    - JP_RDS_END_POINT=festival.c8yvg2qxmek7.ap-northeast-2.rds.amazonaws.com
    - JP_RDS_PORT=3306
    - JP_RDS_SCHEMA=iriscalender
    - JP_RDS_USERNAME=miraedbswo
    - secure: KPeYoaP/aCkO0R79dTiRXBD9txgMJ98xx4gki6WDRsAXs4bjG679/XekzQAk7M0ioandxHCYibGqSbLFR+OmEt/V8o5Dbo3OmQxhnapYSi3OpDXlHPj5SDXQMNxVC10WUVwZ0XmjTl87etN5zoJkE7+pgDNQnQmdyLovxDqZYexbfMU8inrV9MspiNsY6E1I+RSW583l3k8nRBDZ9ZqcIUTTe+ZyC67vq90I+HCoW/QFZXP9eWJPx3yqYWMi1O8WOJhcxBJmb4BNVZGsJNPr6/2ha+delaW5qW3Am9yZF2e5d5Brj3kn97e2TsqGHc7IRXUqcvkyA/LzSkkq3Lz/fEC2hNLFRV5JV4OR7uyrJervyxEReFWNXejWBTeYeuw6jDEr5hpV6wC8IepxeqXn3gmV0FW5X0uXJlcv4O8/i5peOS0CUDRRtJRvf4UNg4KY2i37BNczmnlxfWvcoKBnYEeOGJz1XSBeE534A5K+WdDUEI89UeRtwYafkdx6BdB7VeDSMLTxDq+A+sv2V7rgH48RfIgSsMFTLZUTTW1zHnZFwEuLTUXSOte+Ur9CsJ7Emrjo0/waJG1KDMFWKjs3WP342onKbwD2uD0TEEmdmEz3uEQX4hnyqFoG0Par71Gcicp0rIAWOeY5YD2/Egjfb9yc1YCedw8tlRh1YrNkC2I=
