server:
  port: 5000

server.error:
  include-exception: false
  include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부
  path: '/error' # 오류 응답을 처리할 Handler의 경로
  whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부


spring:
  datasource:
    url: jdbc:mysql://${JP_RDS_END_POINT}:${JP_RDS_PORT}/${JP_RDS_SCHEMA}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${JP_RDS_USERNAME}
    password: ${JP_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update