swagger: "2.0"
info:
  description: "Java Project"
  version: "0.0.1"
  title: "iris calender"
#host: ""
basePath: "/"
tags:
  - name: "Account"
    description: "계정 관련 api"
  - name: "Allocation"
    description: "할당 시간 관련 api"
  - name: "Category"
    description: "카테고리 관련 api"
  - name: "Calender"
    description: "일정 관리 api"
schemes:
  - "https"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /auth/signup:
    post:
      tags:
        - "Account"
      summary: "Register user by id and password"
      description: "회원가입"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Registration params"
          required: true
          schema:
            $ref: "#/definitions/SignupParam"
      responses:
        201:
          description: "User created and returns uuid and token"
          schema:
            $ref: '#/definitions/SignupResponse'
        400:
          description: "Invalid registration value"
        409:
          description: "User already exists"
        500:
          description: "Internal Server Error"
  /auth/login:
    post:
      tags:
        - "Account"
      summary: "login by id and password"
      description: "로그인"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login params"
          required: true
          schema:
            $ref: "#/definitions/LoginParam"
      responses:
        200:
          description: "success to verify user"
          schema:
            $ref: '#/definitions/SignupResponse'
        400:
          description: "Invalid value"
        500:
          description: "Internal Server Error"
  /time:
    post:
      tags:
        - "Allocation"
      summary: "set allocation time"
      description: "할당 시간 설정"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Allocation params"
          required: true
          schema:
            $ref: "#/definitions/AllocationParam"
      responses:
        200:
          description: "success to allocate time"
        400:
          description: "Invalid value"
        500:
          description: "Internal Server Error"
  /time/<uuid>:
    get:
      tags:
        - "Allocation"
      summary: "get allocation time"
      description: "할당 시간 조회"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "url"
          name: "uuid"
          description: "user uuid"
          required: true
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/AllocationParam"
        204:
          description: "No user matches uuid"
        400:
          description: "Invalid value"
        500:
          description: "Internal Server Error"
    patch:
      tags:
        - "Allocation"
      summary: "update allocation time"
      description: "할당 시간 수정"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "url"
          name: "uuid"
          description: "user uuid"
          required: true
        - in: "body"
          name: "body"
          description: "Allocation params"
          required: true
          schema:
            $ref: "#/definitions/AllocationParam"
      responses:
        200:
          description: "success"
        400:
          description: "Invalid value"
        500:
          description: "Internal Server Error"


definitions:
  SignupParam:
    type: "object"
    required:
      - id
      - password1
      - password2
    properties:
      id:
        type: "string"
        description: user id, minlength 6
      password1:
        type: "string"
        format: "password"
        description: minlength 8, AlphanumericPassword
      password2:
        type: "string"
        format: "password"
        description: check if same as password1
  LoginParam:
    type: "object"
    required:
      - id
      - password
    properties:
      id:
        type: "string"
        description: user id, minlength 6
      password:
        type: "string"
        format: "password"
        description: minlength 8, AlphanumericPassword
  AllocationParam:
    type: "object"
    required:
      - startTime
      - endTime
    properties:
      startTime:
        type: "string"
        example: "10:30"
        description: 할당 시간 중 시작 시간
      endTime:
        type: "string"
        example: "22:30"
        description: 할당 시간 중 끝 시간
  SignupResponse:
    description: returns uuid & access token
    type: "object"
    properties:
      uuid:
        type: "string"
        format: "uuid"
      token:
        type: "string"
        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTY0NjQ2NzIwLCJqdGkiOiJlMGNmZjc1MWIwMTU0OTAzOTllMGM
